---
version: "3"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: lab
    hostname: lab #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
#      - PUBLIC_KEY=yourpublickey #optional
#      - PUBLIC_KEY_FILE=/path/to/file #optional
#      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
#      - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=passw0rd #optional
#      - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=codesenju #optional
#    volumes:
#      - /path/to/appdata/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped